# -*- coding: utf-8 -*-
"""Doc2pdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohtirzs3AJhiuEZDfIsDCHf7a1xO9gps
"""



"""# Task
Create a tool that converts multiple `.doc` files to `.pdf` sequentially within Google Colab, leveraging LibreOffice for conversion and `ipywidgets` for an interactive user interface.

## Install LibreOffice

### Subtask:
Install LibreOffice and its dependencies. LibreOffice will be used to convert `.doc` files to `.pdf` while preserving the original formatting. This step ensures the necessary conversion tool is available in the Colab environment.

**Reasoning**:
First, I'll update the package lists to ensure that the system has the latest information about available packages before attempting to install LibreOffice.
"""

print("Updating package lists...")
!apt-get update

"""**Reasoning**:
Now that the package lists are updated, I will install the `libreoffice` package to make it available in the Colab environment for document conversion.


"""

print("Installing LibreOffice...")
!apt-get install -y libreoffice

"""**Reasoning**:
Now that LibreOffice has been installed, I will verify its installation by checking its version to ensure the command is available and working.


"""

print("Verifying LibreOffice installation...")
!libreoffice --version

"""## Define Conversion Function

### Subtask:
Create a Python function that converts a .doc or .docx file to PDF using LibreOffice.

**Reasoning**:
To achieve the subtask of converting .doc/.docx files to PDF, I will create a Python function that uses the `subprocess` module to execute the LibreOffice conversion command, handles file paths, and returns the path to the converted PDF.
"""

import subprocess
import os

def convert_doc_to_pdf(input_filepath: str, output_dir: str) -> str:
    """
    Converts a .doc or .docx file to PDF using LibreOffice.

    Args:
        input_filepath (str): The path to the input .doc or .docx file.
        output_dir (str): The directory where the converted PDF should be saved.

    Returns:
        str: The full path to the converted PDF file.

    Raises:
        subprocess.CalledProcessError: If LibreOffice conversion fails.
    """
    print(f"Converting {input_filepath} to PDF...")

    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Construct the LibreOffice command
    # --headless: Run without a graphical user interface
    # --convert-to pdf: Specify output format as PDF
    # --outdir <output_dir>: Specify the output directory
    # <input_filepath>: The input document file
    command = [
        "libreoffice",
        "--headless",
        "--convert-to",
        "pdf",
        "--outdir",
        output_dir,
        input_filepath
    ]

    try:
        # Execute the command
        # capture_output=True: Capture stdout and stderr
        # text=True: Decode stdout and stderr as text
        # check=True: Raise a CalledProcessError if the command returns a non-zero exit code
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        print("LibreOffice stdout:", result.stdout)
        if result.stderr:
            print("LibreOffice stderr:", result.stderr)

        # Determine the name of the output PDF file
        base_name = os.path.basename(input_filepath)
        file_name_without_ext = os.path.splitext(base_name)[0]
        output_pdf_name = f"{file_name_without_ext}.pdf"
        output_pdf_path = os.path.join(output_dir, output_pdf_name)

        if os.path.exists(output_pdf_path):
            print(f"Successfully converted to {output_pdf_path}")
            return output_pdf_path
        else:
            raise FileNotFoundError(f"Conversion successful but output file not found: {output_pdf_path}")

    except subprocess.CalledProcessError as e:
        print(f"Error during conversion: {e}")
        print(f"Command: {' '.join(e.cmd)}")
        print(f"Return Code: {e.returncode}")
        print(f"Output: {e.stdout}")
        print(f"Error Output: {e.stderr}")
        raise # Re-raise the exception after logging
    except FileNotFoundError as e:
        print(f"Error: {e}")
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise

print("Defined function: convert_doc_to_pdf")

"""## Setup Interactive UI

### Subtask:
Initialize ipywidgets to create an interactive user interface with an output area, an upload button, a convert button, and a download button, encapsulated in a function.

**Reasoning**:
I will import the necessary `ipywidgets` and `IPython.display` modules and then define the `setup_ui` function that initializes an output area, an upload button, a convert button, and a download button, returning these widgets as requested by the subtask.
"""

import ipywidgets as widgets
from IPython.display import display

def setup_ui():
    """
    Initializes and returns interactive UI components for file conversion.

    Returns:
        tuple: A tuple containing (output_area, upload_button, convert_button, download_button).
    """
    # 3. Create an Output widget
    output_area = widgets.Output(layout={'border': '1px solid black'})

    # 4. Create a Button widget for file uploads
    upload_button = widgets.Button(
        description='Upload .doc/.docx File',
        disabled=False,
        button_style='primary', # 'success', 'info', 'warning', 'danger' or ''
        tooltip='Click to upload .doc or .docx files',
        icon='upload'
    )

    # 5. Create a Button widget to trigger conversion
    convert_button = widgets.Button(
        description='Ready to Convert',
        disabled=True, # Initially disabled until files are uploaded
        button_style='info',
        tooltip='Click to convert uploaded files to PDF',
        icon='file-export'
    )

    # 6. Create a Button widget for downloading the converted PDF
    download_button = widgets.Button(
        description='Download PDF',
        disabled=True, # Initially disabled until conversion is complete
        button_style='success',
        tooltip='Click to download the converted PDF file',
        icon='download'
    )

    # 7. Return all created widgets
    return output_area, upload_button, convert_button, download_button

print("Defined function: setup_ui")

"""## Handle File Upload

### Subtask:
Implement the logic for the upload button, including displaying the UI, processing uploaded files, and updating button states.

**Reasoning**:
I need to import necessary modules, initialize a global list for uploaded files, call the UI setup function, and then define and attach the callback logic for the upload button to handle file uploads, save them, and update button states.
"""

from google.colab import files
from IPython.display import clear_output

# 2. Define a global variable for uploaded files
uploaded_files_queue = []

# 3. Call setup_ui() to get the widgets
output_area, upload_button, convert_button, download_button = setup_ui()

def on_upload_button_clicked(button):
    """
    Callback function to handle file uploads.
    """
    with output_area:
        clear_output(wait=True) # Clear previous outputs in this area
        print("Please select your .doc or .docx files to upload...")

        try:
            uploaded = files.upload()
        except Exception as e:
            print(f"An error occurred during file upload: {e}")
            return

        if not uploaded:
            print("No files were uploaded.")
            convert_button.disabled = True
            download_button.disabled = True
            return

        uploaded_files_queue.clear() # Clear previous uploads
        for filename, content in uploaded.items():
            # Save the uploaded file content to a temporary file
            with open(filename, 'wb') as f:
                f.write(content)
            uploaded_files_queue.append(filename)
            print(f"Uploaded and saved: {filename}")

        if uploaded_files_queue:
            convert_button.disabled = False # Enable convert button
            download_button.disabled = True # Disable download button until conversion
            print(f"Successfully uploaded {len(uploaded_files_queue)} file(s). Convert button is now enabled.")
        else:
            convert_button.disabled = True
            download_button.disabled = True
            print("No valid files were processed.")

# 5. Attach the callback function to the upload button
upload_button.on_click(on_upload_button_clicked)

# 6. Display the UI components
display(upload_button, convert_button, download_button, output_area)

"""## Trigger Conversion

### Subtask:
Implement the logic for the 'Ready to Convert' button. Once files are uploaded and this button is clicked, it will call the previously defined conversion function for each uploaded file, provide user feedback, and enable the download button.

**Reasoning**:
I will define the global list `converted_pdf_paths` and then implement the `on_convert_button_clicked` function to handle file conversions, update UI states, and provide feedback as specified in the instructions.
"""

converted_pdf_paths = [] # Global list to store paths of converted PDFs

def on_convert_button_clicked(button):
    """
    Callback function to handle file conversion.
    """
    global converted_pdf_paths

    with output_area:
        clear_output(wait=True)
        print("Starting conversion process...")
        converted_pdf_paths.clear() # Clear previous converted paths

        output_pdf_dir = "converted_pdfs"
        os.makedirs(output_pdf_dir, exist_ok=True)

        if not uploaded_files_queue:
            print("No files to convert. Please upload files first.")
            convert_button.disabled = True
            download_button.disabled = True
            return

        for input_filepath in uploaded_files_queue:
            try:
                pdf_path = convert_doc_to_pdf(input_filepath, output_pdf_dir)
                converted_pdf_paths.append(pdf_path)
                print(f"Converted '{input_filepath}' to '{pdf_path}'")
            except Exception as e:
                print(f"Failed to convert '{input_filepath}': {e}")

        if converted_pdf_paths:
            download_button.disabled = False
            print(f"\nConversion complete. {len(converted_pdf_paths)} file(s) converted. Download button is now enabled.")
        else:
            download_button.disabled = True
            print("\nConversion completed, but no files were successfully converted.")

# Attach the callback function to the convert button
convert_button.on_click(on_convert_button_clicked)

print("Conversion logic for 'Ready to Convert' button defined.")

"""## Provide Download and Restart

### Subtask:
After successful conversion, display a download button for the generated PDF file using `google.colab.files.download()`. Immediately after providing the download option, the interactive UI will reset, allowing the user to upload a new file and restart the conversion process for another document without needing to rerun the entire code cell.

**Reasoning**:
I will define the `on_download_button_clicked` function to handle downloading all converted PDF files, then reset the global queues and UI button states to prepare for new uploads, as per the subtask instructions.
"""

def on_download_button_clicked(button):
    """
    Callback function to handle downloading converted PDF files and resetting the UI.
    """
    global uploaded_files_queue, converted_pdf_paths

    with output_area:
        clear_output(wait=True)
        print("Starting downloads...")

        if not converted_pdf_paths:
            print("No PDFs available for download.")
            return

        for pdf_path in converted_pdf_paths:
            try:
                print(f"Downloading {os.path.basename(pdf_path)}...")
                files.download(pdf_path)
            except Exception as e:
                print(f"Failed to download {os.path.basename(pdf_path)}: {e}")

        # Reset for new uploads
        uploaded_files_queue.clear()
        converted_pdf_paths.clear()

        convert_button.disabled = True
        download_button.disabled = True

        clear_output(wait=True)
        print("Downloads complete. UI has been reset. Ready for new uploads.")

# Attach the callback function to the download button
download_button.on_click(on_download_button_clicked)

print("Download and UI reset logic defined.")

"""## Final Task

### Subtask:
Provide a summary of the completed document conversion tool, highlighting its features and ease of use for converting multiple `.doc` files to `.pdf` sequentially within the Colab environment.

## Summary:

### Data Analysis Key Findings
*   **Integrated Conversion Tool Development**: A comprehensive tool was successfully developed within the Google Colab environment to convert multiple `.doc` or `.docx` files to `.pdf` sequentially.
*   **LibreOffice Integration**: LibreOffice version 7.3.7.2 was successfully installed and utilized as the backend for document conversion, ensuring accurate preservation of formatting.
*   **Core Conversion Function**: A Python function, `convert_doc_to_pdf`, was implemented to handle the conversion process, including robust error handling for failed conversions and proper management of output directories.
*   **Interactive User Interface**: An `ipywidgets`-based interactive UI was established, featuring:
    *   An `output_area` for user feedback.
    *   An `upload_button` for selecting `.doc` or `.docx` files.
    *   A `convert_button` to initiate the conversion process.
    *   A `download_button` for retrieving the converted PDF files.
*   **Sequential File Processing**: The tool is designed to process uploaded files sequentially, converting each `.doc`/`.docx` file to its corresponding `.pdf` format.
*   **Dynamic UI State Management**: The UI dynamically updates button states (e.g., `convert_button` enabled after upload, `download_button` enabled after successful conversion) to guide the user through the workflow.
*   **Batch Download and Reset Functionality**: After conversion, the tool allows for batch downloading of all generated PDF files using `google.colab.files.download()`. Critically, it then resets the UI and clears temporary data (`uploaded_files_queue`, `converted_pdf_paths`), enabling users to immediately begin a new conversion process without needing to rerun the Colab cell.

### Insights or Next Steps
*   **Enhance File Type Support**: Extend the `convert_doc_to_pdf` function to support additional document formats (e.g., `.odt`, `.rtf`) that LibreOffice can convert, broadening the tool's utility.
*   **Asynchronous Conversion for Large Files**: For very large documents or a high volume of files, consider implementing asynchronous processing or background tasks to prevent UI freezes and provide more continuous feedback during lengthy conversions.
"""